import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './providers/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <Providers>
        <body className='flex min-h-screen flex-col'>
        {children}
      </body>
      </Providers>
      
    </html>
  )
}