import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers/providers";
import Header from "@/components/header"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="flex min-h-screen flex-col">
        <Providers>
          <Header/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
